version: '3.8'

services:
  backend:
    build: .
    container_name: tribe_offers_microservices_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=tribe_offers_microservices_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_NAME=tribo_ofertas
    depends_on:
      db:
        condition: service_healthy
      - coupon_service
      - transaction_service
      - qr_code_service
      - offer_update_service

  db:
    image: postgres:14
    container_name: tribe_offers_microservices_db
    environment:
      POSTGRES_DB: tribo_ofertas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  coupon_service:
    build: ./microservices/coupon_service
    ports:
      - "8084:8084" 

  transaction_service:
    build: ./microservices/transaction_service
    ports:
      - "8085:8085"  

  qr_code_service:
    build: ./microservices/qr_code_service
    ports:
      - "8086:8086"

  offer_update_service:
    build: ./microservices/offer_update_service
    ports:
      - "8087:8087"

  pgadmin:
    image: dpage/pgadmin4
    container_name: tribe_offers_microservices_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  postgres_data:
