version: '3.8'

services:
  backend:
    build: .
    container_name: tribo_ofertas_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=tribo_ofertas_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_NAME=tribo_ofertas
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    container_name: tribo_ofertas_db
    environment:
      POSTGRES_DB: tribo_ofertas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: tribo_ofertas_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  postgres_data:

