version: '3.8'

services:
  backend:
    build: .
    container_name: tribe_offers_microservices_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=tribe_offers_microservices_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_NAME=tribo_ofertas
    depends_on:
      db:
        condition: service_healthy
      coupon_generation_service:
        condition: service_started
      transaction_service:
        condition: service_started
      qr_code_service:
        condition: service_started
      offer_update_service:
        condition: service_started
      offer_ranking_service:
        condition: service_started
      coupon_redemption_service:
        condition: service_started
      coupon_evaluation_service:
        condition: service_started   
               
  db:
    image: postgres:14
    container_name: tribe_offers_microservices_db
    environment:
      POSTGRES_DB: tribo_ofertas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  coupon_generation_service:
    build: ./microservices/coupon_generation_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=tribe_offers_microservices_db
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_NAME=tribo_ofertas
      - DB_PORT=5432
    ports:
      - "8084:8084" 

  transaction_service:
    build: ./microservices/transaction_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=tribe_offers_microservices_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_NAME=tribo_ofertas    
    ports:
      - "8085:8085"  

  qr_code_service:
    build: ./microservices/qr_code_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=tribe_offers_microservices_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_NAME=tribo_ofertas    
    ports:
      - "8086:8086"
    volumes:
      - ./output:/app/output  # Mapeando o diretório local ./output para /app/output no container  

  offer_update_service:
    build: ./microservices/offer_update_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=tribe_offers_microservices_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_NAME=tribo_ofertas
    ports:
      - "8087:8087"

  offer_ranking_service:
    build: ./microservices/offer_ranking_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=tribe_offers_microservices_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_NAME=tribo_ofertas
    ports:
      - "8088:8088"

  coupon_redemption_service:
    build: ./microservices/coupon_redemption_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=tribe_offers_microservices_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_NAME=tribo_ofertas
    ports:
      - "8089:8089"
    volumes:
      - ./output:/app/output  # Mapeando o diretório local ./output para /app/output no container  

  coupon_evaluation_service:
    build: ./microservices/coupon_evaluation_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=tribe_offers_microservices_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_NAME=tribo_ofertas
    ports:
      - "8090:8090"
    volumes:
      - ./output:/app/output 
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: tribe_offers_microservices_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  postgres_data:
